#
# Copyright (C) 2025 The LineageOS Project
#
# SPDX-License-Identifier: Apache-2.0
#

# This file is generated by device/samsung/gta9/setup-makefiles.sh

PRODUCT_COPY_FILES += \
    $(call find-copy-subdir-files,*,vendor/samsung/gta9/proprietary/vendor_dlkm,$(TARGET_COPY_OUT_VENDOR_DLKM))
